import express from 'express'; import cors from 'cors'; import jwt from 'jsonwebtoken'; import bcrypt from 'bcryptjs'; import {z} from 'zod'; import {pool,tx} from './db.js'; import 'dotenv/config';
const app=express(), secret=process.env.JWT_SECRET||'development-secret'; app.use(cors());app.use(express.json({limit:'8mb'}));
type User={id:string;role:string;station_id:string|null;email:string;display_name:string};
const auth=async(req:any,res:any,next:any)=>{try{const token=req.headers.authorization?.replace('Bearer ','');req.user=jwt.verify(token,secret) as User;next()}catch{res.status(401).json({error:'Authentication required'})}};
const roles=(...r:string[])=>(req:any,res:any,next:any)=>r.includes(req.user.role)?next():res.status(403).json({error:'Insufficient permission'});
async function scoped(c:any,u:User){await c.query("select set_config('app.user_id',$1,true),set_config('app.role',$2,true),set_config('app.station_id',$3,true)",[u.id,u.role,u.station_id||''])}
async function audit(c:any,u:User,action:string,type:string,id?:string,detail={}){await c.query('insert into audit_log(actor_id,action,entity_type,entity_id,detail) values($1,$2,$3,$4,$5)',[u.id,action,type,id||null,detail])}
app.post('/api/auth/login',async(req,res)=>{const p=z.object({email:z.string().email(),password:z.string().min(1)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid credentials'});const {rows}=await pool.query('select id,email,display_name,role,station_id,password_hash from users where email=$1 and active=true',[p.data.email]);const u=rows[0];if(!u||!await bcrypt.compare(p.data.password,u.password_hash))return res.status(401).json({error:'Invalid email or password'});const user={id:u.id,email:u.email,display_name:u.display_name,role:u.role,station_id:u.station_id};res.json({token:jwt.sign(user,secret,{expiresIn:'12h'}),user})});
app.get('/api/me',auth,(req:any,res)=>res.json(req.user));
app.get('/api/dashboard',auth,async(req:any,res)=>{const d=await tx(async c=>{await scoped(c,req.user);const q=async(sql:string)=>Number((await c.query(sql)).rows[0].count);return {outOfService:await q("select count(*) from apparatus where status='out_of_service'"),openDeficiencies:await q("select count(*) from deficiencies where status in ('open','assigned','in_progress')"),overdueRepairs:await q("select count(*) from deficiencies where due_date<current_date and status not in ('completed','deferred')"),expiringEquipment:await q("select count(*) from equipment where expiration_date between current_date and current_date+interval '30 days'"),dueToday:await q("select count(*) from apparatus a where not exists(select 1 from inspections i where i.apparatus_id=a.id and i.submitted_at::date=current_date)"),byStation:(await c.query("select s.name,count(i.id) completed from stations s left join apparatus a on a.station_id=s.id left join inspections i on i.apparatus_id=a.id and i.submitted_at>=date_trunc('month',current_date) group by s.id order by s.name")).rows}});res.json(d)});
app.get('/api/apparatus',auth,async(req:any,res)=>{const r=await tx(async c=>{await scoped(c,req.user);return c.query(`select a.*,s.name station,t.name type,it.name checklist from apparatus a join stations s on s.id=a.station_id left join apparatus_types t on t.id=a.type_id left join inspection_templates it on it.id=a.checklist_id where ($1='' or a.unit_number ilike $1 or a.name ilike $1) order by a.unit_number`,[req.query.q?`%${req.query.q}%`:''])});res.json(r.rows)});
app.post('/api/apparatus',auth,roles('administrator','chief_officer','apparatus_officer'),async(req:any,res)=>{const p=z.object({unit_number:z.string().min(1),name:z.string().min(1),station_id:z.string().uuid(),type_id:z.string().uuid().nullable().optional(),vin:z.string().optional(),mileage:z.number().int().nonnegative().default(0),fuel_level:z.number().min(0).max(100).optional(),status:z.enum(['available','limited','out_of_service']).default('available'),in_service:z.boolean().default(true),checklist_id:z.string().uuid().nullable().optional()}).parse(req.body);const r=await tx(async c=>{await scoped(c,req.user);const x=await c.query('insert into apparatus(unit_number,name,station_id,type_id,vin,mileage,fuel_level,status,in_service,checklist_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *',Object.values(p));await audit(c,req.user,'create','apparatus',x.rows[0].id);return x});res.status(201).json(r.rows[0])});
app.get('/api/templates/:id',auth,async(req:any,res)=>{const template=await pool.query('select * from inspection_templates where id=$1',[req.params.id]);const questions=await pool.query('select * from inspection_questions where template_id=$1 order by display_order',[req.params.id]);res.json({template:template.rows[0],questions:questions.rows})});
app.post('/api/inspections',auth,async(req:any,res)=>{const p=z.object({apparatus_id:z.string().uuid(),template_id:z.string().uuid(),signature_name:z.string().min(2),notes:z.string().optional(),responses:z.array(z.object({question_id:z.string().uuid(),response:z.enum(['pass','fail','na','attention']),note:z.string().optional(),photo_url:z.string().optional()})).min(1)}).parse(req.body);for(const r of p.responses)if(['fail','attention'].includes(r.response)&&!r.note)return res.status(400).json({error:'Failed or attention items require a note'});const x=await tx(async c=>{await scoped(c,req.user);const i=(await c.query("insert into inspections(apparatus_id,template_id,inspector_id,status,submitted_at,signature_name,notes) values($1,$2,$3,'submitted',now(),$4,$5) returning *",[p.apparatus_id,p.template_id,req.user.id,p.signature_name,p.notes||null])).rows[0];for(const r of p.responses){const response=(await c.query('insert into inspection_responses(inspection_id,question_id,response,note,photo_url) values($1,$2,$3,$4,$5) returning *',[i.id,r.question_id,r.response,r.note||null,r.photo_url||null])).rows[0];if(['fail','attention'].includes(r.response)){const question=(await c.query('select question from inspection_questions where id=$1',[r.question_id])).rows[0];await c.query("insert into deficiencies(apparatus_id,inspection_id,response_id,title,description,severity,created_by) values($1,$2,$3,$4,$5,$6,$7)",[p.apparatus_id,i.id,response.id,question.question,r.note,r.response==='fail'?'high':'medium',req.user.id])}}await audit(c,req.user,'submit','inspection',i.id);return i});res.status(201).json(x)});
app.get('/api/deficiencies',auth,async(req:any,res)=>{const r=await tx(async c=>{await scoped(c,req.user);return c.query("select d.*,a.unit_number,u.display_name assigned_name from deficiencies d left join apparatus a on a.id=d.apparatus_id left join users u on u.id=d.assigned_to where ($1='' or d.status=$1) order by d.created_at desc",[req.query.status||''])});res.json(r.rows)});
app.patch('/api/deficiencies/:id',auth,roles('administrator','chief_officer','apparatus_officer','maintenance_user'),async(req:any,res)=>{const p=z.object({assigned_to:z.string().uuid().nullable().optional(),due_date:z.string().date().nullable().optional(),status:z.enum(['open','assigned','in_progress','completed','deferred']).optional()}).parse(req.body);const fields=Object.keys(p);if(!fields.length)return res.status(400).end();const values=Object.values(p);const sets=fields.map((x,i)=>`${x}=$${i+1}`).join(',');const r=await tx(async c=>{await scoped(c,req.user);const x=await c.query(`update deficiencies set ${sets}, completed_at=case when $${fields.length+1}='completed' then now() else completed_at end where id=$${fields.length+2} returning *`,[...values,p.status||'',req.params.id]);await audit(c,req.user,'update','deficiency',req.params.id,p);return x});res.json(r.rows[0])});
app.post('/api/repairs',auth,roles('administrator','chief_officer','maintenance_user'),async(req:any,res)=>{const p=z.object({deficiency_id:z.string().uuid(),repair_notes:z.string().min(1),parts:z.string().optional(),cost:z.number().nonnegative().default(0),completed_at:z.string().optional()}).parse(req.body);const r=await tx(async c=>{await scoped(c,req.user);const x=await c.query('insert into repair_records(deficiency_id,performed_by,repair_notes,parts,cost,completed_at) values($1,$2,$3,$4,$5,$6) returning *',[p.deficiency_id,req.user.id,p.repair_notes,p.parts||null,p.cost,p.completed_at||null]);if(p.completed_at)await c.query("update deficiencies set status='completed',completed_at=now() where id=$1",[p.deficiency_id]);await audit(c,req.user,'repair','deficiency',p.deficiency_id);return x});res.status(201).json(r.rows[0])});
app.get('/api/export/deficiencies.csv',auth,async(req:any,res)=>{const r=await pool.query("select d.id,a.unit_number,d.title,d.severity,d.status,d.due_date,d.created_at from deficiencies d left join apparatus a on a.id=d.apparatus_id order by d.created_at desc");const esc=(v:any)=>'"'+String(v??'').replaceAll('"','""')+'"';res.type('text/csv').attachment('deficiencies.csv').send(['ID,Unit,Title,Severity,Status,Due Date,Created',...r.rows.map(x=>Object.values(x).map(esc).join(','))].join('\n'))});
app.listen(Number(process.env.PORT||3001),'0.0.0.0',()=>console.log('API on 3001'));
